mysite/forum/urls.py
from django.urls import path
from . import views

app_name = "forum"

urlpatterns = [
    path('', views.index, name='index'),
    path('<topic>/', views.forum, name='forum'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

mysite/forum/models.py
from django.db import models

class Topic(models.Model):
    name = models.CharField("トピック名", max_length=20)

    def __str__(self):
        return self.name

class Message(models.Model):
    content = models.CharField("内容", max_length=200)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    created_at = models.DateTimeField("投稿日時", auto_now_add=True)

    def __str__(self):
        return self.content

class Comment(models.Model):
    content = models.CharField("内容", max_length=200)
    created_at = models.DateTimeField("投稿日時", auto_now_add=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="comment")

    def __str__(self):
        return self.content

class Tag(models.Model):
    name = models.CharField("タグ名", max_length=20)
    message = models.ManyToManyField(Message, null=True, blank=True, related_name="tag")

    def __str__(self):
        return self.name

mysite/forum/forms.py
from django import forms

from .models import Message, Tag, Comment

class TagModelChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class MessageForm(forms.ModelForm):
    tag = TagModelChoiceField(
        queryset=Tag.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Message
        fields = [
            "content",
        ]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            "content",
        ]

mysite/forum/views.py
from django.shortcuts import render, redirect
from .models import Topic, Message, Comment
from .forms import MessageForm, CommentForm
from django.db.models import Count, OuterRef, Subquery

def index(request):
    TOPIC_LIST = Topic.objects.all()
    return render(request, "forum/index.html", {"topics": TOPIC_LIST})

def forum(request, topic):

    topic = Topic.objects.get(name=topic)
    subquery = Comment.objects.filter(message=OuterRef('id')).order_by('-created_at')
    messages = (
        Message.objects.filter(topic=topic)
        .annotate(
            reply_num=Count("comment"),
            latest_reply_date=Subquery(subquery.values("created_at")[:1]),
        )
        .prefetch_related("tag", "comment")
        .order_by("created_at")
    )

    if request.method == "POST":

        if "message" in request.POST:

            message_form = MessageForm(request.POST)

            if message_form.is_valid():
                message_form.instance.topic = topic
                message = message_form.save()
                for tag in message_form.cleaned_data["tag"]:
                    message.tag.add(tag)

        elif "comment" in request.POST:

            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():

                message_id = request.POST["comment"]
                message = Message.objects.get(id=message_id)

                comment_form.instance.message = message
                comment_form.save()

        return redirect('forum:forum', topic=topic.name)

    message_form = MessageForm()
    comment_form = CommentForm()

    context = {
        "messages": messages,
        "topic": topic,
        "message_form": message_form,
        "comment_form": comment_form,
    }

    return render(request, "forum/forum.html", context)

mysite/forum/templates/forum/forum.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Forum アプリケーション</title>
    <link rel="stylesheet" type="text/css" href="{% static 'forum/css/forum.css' %}" />
</head>
<body>
    <h1>掲示板</h1>
    <h2>{{ topic.name }}</h2>
    <table>
    {% for message in messages %}
    <form action="{% url 'forum:forum' topic.name %}" method="POST">
        {% csrf_token %}
        <tr>
            <tr>
                <th>{{ message.content }}</th>
                <th>{{ message.created_at }}</th>
                {% for tag in message.tag.all %}
                    <th>{{ tag.name }}</th>
                {% endfor %}
                <th>コメント数 : {{ message.reply_num }}</th>
                <th>最新コメント : {{ message.latest_reply_date }}</th>
            </tr>
            {% for comment in message.comment.all %}
            <tr>
                <th>{{ comment.content }}</th>
                <th>{{ comment.created_at }}</th>
            </tr>
            {% endfor %}
            <tr>
                <th>{{ comment_form }}</th>
                <th><button type="submit" name="comment" value="{{ message.id }}">コメント</button></th>
            </tr>
        </tr>
    </form>
    {% endfor %}
    </table>
    <form action="{% url 'forum:forum' topic.name %}" method="POST">
        {% csrf_token %}
        {{ message_form }}
        <button type="submit" name="message" value="value">送信</button>
    </form>
    <a href="{% url 'forum:index' %}">ホームへ</a>
</body>
</html>

mysite/forum/templates/forum/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <title>Forum アプリケーション</title>
    <link rel="stylesheet" type="text/css" href="{% static 'forum/css/index.css' %}" />
</head>

<body>
    <h1>Forum</h1>
    <h2>各掲示板へのリンク</h2>
    <table>
        {% for topic in topics %}
        {% if topic != "Swift" and topic != "Kotlin" %}
        <tr>
            <th>
                {{ topic }}
            </th>
            <td>
                <a href="{% url 'forum:forum' topic %}">{{ topic }}の掲示板へ</a>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</body>

</html>